language: java
jdk:
  - openjdk8

#services:
#  - mysql

#before_install:
#  - chmod +x mvnw

install: skip

script: "mvn clean package -Dmaven.test.skip=true"

#deploy:
#  - ./deploy.sh

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.m2